name: Notion2Readme

on:
  push:
    branches:
      - master
      - develop

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Notion2Readme
        uses: mcschmitz/notion2readme@master
        with:
          url: 'https://www.notion.so/ebot7/Kubeflow-9bc53bb210f743bfa857cb246877c0a0'
        env:
          TOKEN_V2: ${{ secrets.token_v2 }}
      - uses: actions/checkout@v2
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "NOTION2README"
          git push
